config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("orders/", include("orders.urls")),
    path("", include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("ipn/", views.OrderInstantPaymentNotificationView.as_view(), name="ipn"),
    path("my/", views.MyOrderView.as_view(), name="my_order"),
]

products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    path("", views.ProductsView.as_view(), name="list"),
    path("carts/", views.CartsView.as_view(), name="carts"),
    path("carts/<str:slug>/add/", views.CartAddView.as_view(), name="cart-add"),
    path(
        "carts/<str:slug>/remove/", views.CartRemoveView.as_view(), name="cart-remove"
    ),
    path(
        "carts/<str:slug>/delete/", views.CartDeleteView.as_view(), name="cart-delete"
    ),
    path(
        "carts/<str:slug>/checked/",
        views.CartCheckedView.as_view(),
        name="cart-checked",
    ),
    path("<str:slug>/", views.ProductView.as_view(), name="detail"),
]

products/models.py
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from tinymce.models import HTMLField

from accounts.models import User

from .utils import slugify


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


class ProductManager(models.Manager):
    def published(self, **kwargs):
        return self.filter(status=Product.ProductStatus.PUBLISHED, **kwargs)


class Product(models.Model):
    id = models.UUIDField(
        primary_key=True, blank=True, editable=False, serialize=False, unique=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products"
    )
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    discount_price = models.IntegerField("Price")
    price = models.IntegerField("Discount Price", blank=True)
    quantity = models.IntegerField()
    thumbnail = models.ImageField(upload_to="products/thumbnails/")
    description = HTMLField()

    class ProductStatus(models.TextChoices):
        DRAFT = "DR", "Draft"
        PUBLISHED = "PB", "Published"
        ARCHIVED = "AR", "Archived"

    status = models.CharField(
        max_length=2,
        choices=ProductStatus.choices,
        default=ProductStatus.DRAFT,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    def __str__(self) -> str:
        return self.title

    def clean(self):
        if self.price is not None:
            if self.discount_price < self.price:
                raise ValidationError(
                    {"price": "Discount price must be less than price"}
                )

    def save(self, *args, **kwargs) -> None:
        if not self.id:
            self.id = uuid4()
        self.slug = slugify(self.title)
        if not self.price:
            self.price = self.discount_price
        return super().save(*args, **kwargs)

    def has_inventory(self):
        return self.quantity > 0

    def is_new(self, date=None):
        date = date or timezone.now()
        return (date - self.created_at).days < 30

    def has_discount(self):
        return self.discount_price != self.price

    def get_url(self):
        return reverse("products:detail", kwargs={"slug": self.slug})

    def ordered(self, quantity):
        self.quantity -= quantity
        self.save(update_fields=["quantity"])


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to="products/images/")

    def __str__(self) -> str:
        return self.product.title

    def save(self, *args, **kwargs) -> None:
        if ProductImage.objects.filter(product=self.product).count() >= 5:
            raise ValidationError("Only 5 images are allowed per product")
        return super().save(*args, **kwargs)

    @property
    def get_image(self):
        return self.image.url


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carts")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="carts")
    quantity = models.IntegerField()
    is_checked = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.user.email} - {self.product.title}"

    def save(self, *args, **kwargs) -> None:
        if not self.user.is_customer():
            raise ValidationError("Owner are not allowed to add products to cart")

        if self.quantity > self.product.quantity:
            raise ValidationError("Quantity exceeds available stock")

        return super().save(*args, **kwargs)

    def get_total(self):
        return self.product.price * self.quantity

    def get_amount_saved(self):
        return (self.product.discount_price * self.quantity) - (
            self.product.price * self.quantity
        )

    def get_add_url(self):
        return reverse("products:cart-add", kwargs={"slug": self.product.slug})

    def get_remove_url(self):
        return reverse("products:cart-remove", kwargs={"slug": self.product.slug})

    def get_delete_url(self):
        return reverse("products:cart-delete", kwargs={"slug": self.product.slug})

    def get_checked_url(self):
        return reverse("products:cart-checked", kwargs={"slug": self.product.slug})

products/forms.py
from django import forms

from .models import Cart


class CartForm(forms.ModelForm):
    product_slug = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Cart
        fields = ["quantity"]
        widgets = {
            "quantity": forms.NumberInput(
                attrs={
                    "style": "max-width: 22px; text-align: center;",
                    "min": 1,
                    "max": 5,
                    "value": 1,
                }
            ),
        }

products/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Sum
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, View

from .forms import CartForm
from .models import Cart, Product


class ProductsView(ListView):
    model = Product
    paginate_by = 16

    def get_queryset(self):
        return Product.objects.published().select_related("category")


class ProductView(DetailView):
    model = Product

    def get_queryset(self):
        return (
            Product.objects.published()
            .select_related("category")
            .prefetch_related("images")
        )

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, "You must log in for adding cart")
            return redirect("accounts:login")

        form = CartForm(request.POST)
        if form.is_valid():
            product_slug = form.cleaned_data["product_slug"]
            quantity = form.cleaned_data["quantity"]
            cart, created = Cart.objects.get_or_create(
                product=Product.objects.get(slug=product_slug),
                user=request.user,
                defaults={"quantity": quantity},
            )
            if created:
                messages.success(request, "Product added to cart")
            else:
                cart.quantity = form.cleaned_data["quantity"]
                cart.save(update_fields=["quantity"])
                messages.success(request, "Cart already added")
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CartForm(initial={"product_slug": self.object.slug})
        return context


class CartsView(LoginRequiredMixin, ListView):
    model = Cart

    def get_queryset(self):
        Cart.objects.filter(user=self.request.user).update(is_checked=True)
        return (
            Cart.objects.select_related("product")
            .only(
                "quantity",
                "is_checked",
                "product__title",
                "product__slug",
                "product__discount_price",
                "product__price",
            )
            .filter(user=self.request.user)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total"] = (
            Cart.objects.filter(user=self.request.user, is_checked=True)
            .annotate(total=F("product__price") * F("quantity"))
            .aggregate(Sum("total"))["total__sum"]
        )
        return context


class CartAddView(View):
    def post(self, request, slug):
        if not request.user.is_authenticated:
            messages.warning(request, "You must log in for adding cart")
            return redirect("products:list")

        cart = Cart.objects.get(product__slug=slug, user=request.user)
        cart.quantity += 1
        cart.save(update_fields=["quantity"])
        total_price = (
            Cart.objects.filter(user=self.request.user)
            .annotate(total=F("product__price") * F("quantity"))
            .aggregate(Sum("total"))["total__sum"]
        )

        return JsonResponse(
            {
                "added": True,
                "total": cart.get_total(),
                "quantity": cart.quantity,
                "total_price": total_price,
                "has_discount": cart.product.has_discount(),
                "amount_saved": cart.get_amount_saved(),
            }
        )


class CartRemoveView(View):
    def post(self, request, slug):
        if not request.user.is_authenticated:
            messages.warning(request, "You must log in for adding cart")
            return redirect("products:list")

        cart = Cart.objects.get(product__slug=slug, user=request.user)

        data = {}
        data["deleted"] = False
        if cart.quantity == 1:
            data["total"] = cart.get_total()
            cart.delete()
            data["deleted"] = True

        else:
            cart.quantity -= 1
            cart.save(update_fields=["quantity"])
            total_price = (
                Cart.objects.filter(user=self.request.user)
                .annotate(total=F("product__price") * F("quantity"))
                .aggregate(Sum("total"))["total__sum"]
            )
            data["removed"] = True
            data["total"] = cart.get_total()
            data["quantity"] = cart.quantity
            data["total_price"] = total_price
            data["has_discount"] = cart.product.has_discount()
            data["amount_saved"] = cart.get_amount_saved()

        return JsonResponse(data)


class CartDeleteView(View):
    def delete(self, request, slug):
        if not request.user.is_authenticated:
            messages.warning(request, "You must log in for adding cart")
            return redirect("products:list")

        cart = Cart.objects.get(product__slug=slug, user=request.user)
        cart.delete()
        total = (
            Cart.objects.filter(user=self.request.user)
            .annotate(total=F("product__price") * F("quantity"))
            .aggregate(Sum("total"))["total__sum"]
        )
        return JsonResponse({"deleted": True, "total": total})


class CartCheckedView(View):
    def post(self, request, slug):
        if not request.user.is_authenticated:
            messages.warning(request, "You must log in for adding cart")
            return redirect("products:list")

        cart = Cart.objects.get(product__slug=slug, user=request.user)
        cart.is_checked = False
        cart.save(update_fields=["is_checked"])
        return JsonResponse({"checked": cart.is_checked})

templates/products/cart_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container mt-4" style="min-height: 70vh;">
  <div class="table-responsive text-nowrap">
    <div class="mb-4 fs-2 fw-bold">Order Summary</div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" style="width: 1vw;">
            <input type="checkbox" id="allCheck" checked="true">
          </th>
          <th scope="col" style="width: 1vw;">#</th>
          <th scope="col" style="width: 30vw;">Title</th>
          <th scope="col" style="width: 10vw;">Price</th>
          <th scope="col" style="width: 10vw;">Quantity</th>
          <th scope="col" style="width: 10vw;">Total Product Price</th>
        </tr>
      </thead>
      <tbody>
        {% for cart in cart_list %}
        <tr>
          <td>
            <a href="{{ cart.get_checked_url }}"></a>
            <input type="checkbox" class="check">
          </td>
          <td>{{ forloop.counter }}</td>
          <td><a href="{{ cart.product.get_url }}">{{ cart.product.title }}</a></td>
          <td>
            ৳{{ cart.product.price }}
            {% if cart.product.has_discount %}
            <s class="text-danger">৳{{ cart.product.discount_price }}</s>
            {% endif %}
          </td>
          <td>
            <a href="{{ cart.get_remove_url }}"><i class="fas fa-minus mr-2"></i></a>
            <span>{{ cart.quantity }}</span>
            <a href="{{ cart.get_add_url }}"><i class="fas fa-plus ml-2"></i></a>
          </td>
          <td>
            {% if cart.product.has_discount %}
            ৳<span class="getCartTotal">{{ cart.get_total }}</span>
            <span class="badge badge-primary">Saving ৳{{ cart.get_amount_saved }}</span>
            {% else %}
            ৳<span class="getCartTotal">{{ cart.get_total }}</span>
            {% endif %}
            <a style='color: red;' href="{{ cart.get_delete_url }}">
              <i class="fas fa-trash float-right"></i>
            </a>

          </td>
        </tr>
        {% endfor %}
        <tr class="{% if cart_list %}d-none{% endif %} empty">
          <td colspan='6' class="fs-3 text-center py-5">Your cart is empty</td>
        </tr>
        <tr class="{% if cart_list %}d-none{% endif %} empty">
          <td colspan="6">
            <a class='btn btn-primary float-end' href='/'>Continue shopping</a>
          </td>
        </tr>
        <tr class="{% if not cart_list %}d-none{% endif %} non-empty">
          <td colspan="5" class="text-end"><b>Order Total</b></td>
          <td><b>৳<span id="total">{{ total }}</span></b></td>
        </tr>
        <tr class="{% if not cart_list %}d-none{% endif %} non-empty">
          <td colspan="6">
            <a class='btn btn-warning float-end ms-2' id="checkoutBtn" href='{% url "orders:checkout" %}'>Proceed
              to
              checkout</a>
            <a class='btn btn-primary float-end' href='{% url "products:list" %}'>Continue shopping</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

{% endblock body %}

{% block script %}
<script>
  let plus = document.querySelectorAll('.fa-plus');
  let minus = document.querySelectorAll('.fa-minus');
  let trash = document.querySelectorAll('.fa-trash');
  let total = document.getElementById('total');
  let totalValue = parseInt(total.innerHTML);
  let empty = document.querySelectorAll('.empty');
  let non_empty = document.querySelectorAll('.non-empty');
  let allCheck = document.getElementById('allCheck');
  let check = document.querySelectorAll('.check');
  let checkoutBtn = document.getElementById('checkoutBtn');

  check.forEach((item) => {
    item.checked = true;
  });

  plus.forEach((item) => {
    item.addEventListener('click', (e) => {
      e.preventDefault();
      let url = e.target.parentElement.href;
      fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': '{{ csrf_token }}'
        }
      })
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          if (data.added) {
            total.innerHTML = data.total_price;
            e.target.parentElement.previousElementSibling.innerHTML = data.quantity;
            e.target.parentElement.parentElement.nextElementSibling.firstElementChild.innerHTML = data.total;
            totalValue = data.total_price;
            if (data.has_discount) {
              e.target.parentElement.parentElement.nextElementSibling.childNodes[3].innerHTML = `Saving ৳${data.amount_saved}`;
            }
          }
        })
        .catch((error) => {
          console.log(error);
        });
    });
  });

  minus.forEach((item) => {
    item.addEventListener('click', (e) => {
      e.preventDefault();
      let url = e.target.parentElement.href;
      fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': '{{ csrf_token }}'
        }
      })
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          if (data.deleted) {
            e.target.parentElement.parentElement.parentElement.remove();
            totalValue -= data.total;
            total.innerHTML = totalValue;
          } else {
            if (data.removed) {
              total.innerHTML = data.total_price;
              e.target.parentElement.nextElementSibling.innerHTML = data.quantity;
              e.target.parentElement.parentElement.nextElementSibling.firstElementChild.innerHTML = data.total;
              totalValue = data.total_price;
              if (data.has_discount) {
                e.target.parentElement.parentElement.nextElementSibling.childNodes[3].innerHTML = `Saving ৳${data.amount_saved}`;
              }
            }

          }
          if (totalValue <= 0) {
            empty.forEach((item) => {
              item.classList.remove('d-none');
              allCheck.checked = false;
            });
            non_empty.forEach((item) => {
              item.classList.add('d-none');
            });
          }
        })
        .catch((error) => {
          console.log(error);
        });
    });
  });

  trash.forEach((item) => {
    item.addEventListener('click', (e) => {
      e.preventDefault();
      let url = e.target.parentElement.href;
      fetch(url, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': '{{ csrf_token }}'
        }
      })
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          if (data.total <= 0) {
            empty.forEach((item) => {
              item.classList.remove('d-none');
            });
            non_empty.forEach((item) => {
              item.classList.add('d-none');
            });
          }
          if (data.deleted) {
            e.target.parentElement.parentElement.parentElement.remove();
            total.innerHTML = data.total;
            totalValue = data.total;
          }
        })
        .catch((error) => {
          console.log(error);
        });
    });
  });

  allCheck.addEventListener('change', (e) => {
    if (e.target.checked) {
      checkoutBtn.classList.remove('disabled');
    } else {
      checkoutBtn.classList.add('disabled');
    }
    check.forEach((item) => {
      item.checked = e.target.checked;
      if (item.checked) {
        total.innerHTML = totalValue;
      } else {
        total.innerHTML = 0;
      }
    });
  });

  check.forEach((item) => {
    item.addEventListener('change', (e) => {
      let temptotalValue = parseInt(0);
      check.forEach((item) => {
        if (item.checked) {
          temptotalValue += parseInt(item.parentElement.nextElementSibling.nextElementSibling.nextElementSibling.nextElementSibling.nextElementSibling.firstElementChild.innerHTML);
        }
      });
      total.innerHTML = temptotalValue;
      if (temptotalValue == totalValue) {
        allCheck.checked = true;
      } else {
        allCheck.checked = false;
      }
      if (temptotalValue > 0) {
        checkoutBtn.classList.remove('disabled');
      } else {
        checkoutBtn.classList.add('disabled');
      }
    });
  });

  checkoutBtn.addEventListener('click', (e) => {
    e.preventDefault();

    check.forEach((item) => {
      if (!item.checked) {
        let url = item.previousElementSibling.href;
        console.log(url);
        fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
          }
        })
          .then((response) => {
            return response.json();
          })
          .then((data) => {
          })
          .catch((error) => {
            console.log(error);
          });
      }
    });

    let checkoutUrl = e.target.href;
    fetch(checkoutUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': '{{ csrf_token }}'
      },
      body: JSON.stringify({
        'cartCheckout': true
      }),
    })
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        if (data.checkout) {
          window.location.href = data.url;
        }
      })
      .catch((error) => {
        console.log(error);
      });
  });

</script>
{% endblock script %}

templates/products/product_detail.html
{% extends "base.html" %}

{% block body %}

<main class="mt-5 pt-2">
    <div class="container">
        <div class="row">
            <div id="carouselExampleInterval" class="carousel slide col-md-6 mb-4" data-mdb-ride="carousel"
                data-mdb-carousel-init style="height: 100vh;">
                <div class="carousel-inner ">
                    {% for product_img in product.images.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}"
                        data-mdb-interval="{% if forloop.counter == 1 %}10000{% elif forloop.last %}{% else %}2000{% endif %}">
                        <div class="d-flex justify-content-center align-items-center ">
                            <img src="{{product_img.image.url}}" class="img-fluid " alt="Wild Landscape" style="width: 400px; height: 100%;" />
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" data-mdb-target="#carouselExampleInterval" type="button"
                    data-mdb-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true" style="color: black;"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" data-mdb-target="#carouselExampleInterval" type="button"
                    data-mdb-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true" style="color: black;"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <div class="col-md-6 mb-4">
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">{{ product.category }}</span>
                        </a>
                        <a href="">
                            <span class="badge bg-info me-1">New</span>
                        </a>
                        <a href="">
                            <span class="badge bg-danger me-1">Bestseller</span>
                        </a>
                    </div>

                    <p class="lead">
                        {% if product.has_discount %}
                        <span class="me-1 text-danger">
                            <del>৳{{ product.discount_price }}</del>
                        </span>
                        <span>৳{{ product.price }}</span>
                        {% else %}
                        <span>৳{{ product.price }}</span>
                        {% endif %}
                    </p>
                    <strong>
                        <p style="font-size: 20px;">{{ product.title }}</p>
                    </strong>
                    <form class="d-flex justify-content-left" style="margin-top: 100px;" method="post">
                        {% csrf_token %}
                        {{ form.product_slug }}
                        <div>
                            <div class="d-flex flex-row mb-3">
                                <div class="flex-item me-3">Quantity</div>
                                <div class="d-flex flex-row">
                                    <button class="me-2 px-2 addBtn" id="addQuantity">+</button>
                                    <div>
                                        {{ form.quantity }}
                                    </div>
                                    <button class="ms-2 rmBtn" id="removeQuantity" style="padding: 0 .65rem;">-</button>
                                </div>
                            </div>
                            <div>
                                <button class="btn btn-primary ms-1" type="submit" name="add_cart">
                                    Add to cart
                                    <i class="fas fa-shopping-cart ms-1"></i>
                                </button>
                                <button class="btn btn-info ms-1" type="submit" name="buy_now">
                                    Buy Now
                                    <i class="fas fa-shopping-cart ms-1"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- <strong>
                        <p style="font-size: 15px; margin-bottom: 1px; margin-top: 20px;">Description</p>
                    </strong>

                    <p>{{ product.description|safe }}</p> -->
                </div>
            </div>
        </div>
        <hr />
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                    odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in
                    laborum.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid"
                    alt="" />
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid"
                    alt="" />
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid"
                    alt="" />
            </div>
        </div>
    </div>
</main>

{% endblock body %}

{% block script %}
<script>
    let addQuantity = document.getElementById("addQuantity");
    let removeQuantity = document.getElementById("removeQuantity");
    let quantity = document.getElementById("id_quantity");
    addQuantity.addEventListener("click", (e) => {
        e.preventDefault();

        if (quantity.value < 5) {
            removeQuantity.disabled = false;
            removeQuantity.classList.remove("disabled-cursor");
            quantity.value = parseInt(quantity.value) + 1;
        } else {
            addQuantity.disabled = true
            addQuantity.classList.add("disabled-cursor");
        }
    })
    removeQuantity.addEventListener("click", (e) => {
        e.preventDefault();

        if (quantity.value > 1) {
            addQuantity.disabled = false;
            addQuantity.classList.remove("disabled-cursor");
            quantity.value = parseInt(quantity.value) - 1;
        } else {
            removeQuantity.disabled = true;
            removeQuantity.classList.add("disabled-cursor");
        }
    })
</script>
{% endblock script %}