accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("orders/", include("orders.urls")),
    path("", include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("ipn/", views.OrderInstantPaymentNotificationView.as_view(), name="ipn"),
    path("my/", views.MyOrderView.as_view(), name="my_order"),
]

products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    path("", views.ProductsView.as_view(), name="list"),
    path("carts/", views.CartsView.as_view(), name="carts"),
    path("carts/<str:slug>/add/", views.CartAddView.as_view(), name="cart-add"),
    path(
        "carts/<str:slug>/remove/", views.CartRemoveView.as_view(), name="cart-remove"
    ),
    path(
        "carts/<str:slug>/delete/", views.CartDeleteView.as_view(), name="cart-delete"
    ),
    path(
        "carts/<str:slug>/checked/",
        views.CartCheckedView.as_view(),
        name="cart-checked",
    ),
    path("<str:slug>/", views.ProductView.as_view(), name="detail"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  {% include "header.html" %}
</head>

<body>

  {% include "navbar.html" %}

  <div class="">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show d-flex justify-content-between"
      data-mdb-alert-init>
      <div class="ps-5">{{ message }}</div>
      <div>
        <button type="button" class="alert-dismissible " data-mdb-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% block body %}
  {% endblock body %}


  {% include "footer.html" %}
  {% include "script.html" %}

  {% block script %}
  {% endblock script %}

</body>

</html>

templates/footer.html
<footer class="text-center text-white mt-4" style="background-color: #607d8b">
  <hr class="text-dark" />
  <div class="container">
    <section class="mb-3 flex">
      <div>Want to contribute?
        <a class="btn-link btn-floating text-white" href="https://github.com/kazimdkhalednur/OOP_II_Project"
          role="button" data-mdb-ripple-color="dark"><i class="fab fa-github"></i></a>
      </div>
    </section>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); text-color: #e0e0e0">
    Copyright © 2024,
    <a class="text-white" href="https://kazikhalednur.com/">kazikhalednur.com</a>
  </div>
</footer>

templates/header.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>{{ title }}</title>
<!-- MDB icon -->
<link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon" />
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
<!-- Google Fonts Roboto -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
<!-- MDB -->
<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/custom.css' %}" />

templates/navbar.html
{% load static %}
{% load cart_template_tags %}

<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-white">
  <div class="container">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent1"
      aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <a class="navbar-brand mt-2 mt-sm-0" href="{% url 'products:list' %}">
        <img src="{% static 'img/logo.png' %}" height="30" alt="E-Shop Logo" loading="lazy" />
      </a>
    </div>

    <ul class="navbar-nav nav-flex-icons">
      {% if request.user.is_authenticated %}
      <li class="nav-item me-3">
        <a href="{% url 'orders:my_order' %}" class="nav-link waves-effect">
          My Order
        </a>
      </li>
      <li class="nav-item me-3">
        <a href="{% url 'products:carts' %}" class="nav-link waves-effect">
          <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          <i class="fas fa-shopping-cart"></i>
          <span class="badge rounded-pill badge-notification bg-danger" id="cartCount">{{ request.user|cart_count }}</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect" href="{% url 'accounts:logout' %}">
          <span class="clearfix d-none d-sm-inline-block"> Logout </span>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link waves-effect" href="{% url 'accounts:login' %}">
          <span class="clearfix d-none d-sm-inline-block"> Login </span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link waves-effect" href="{% url 'accounts:signup' %}">
          <span class="clearfix d-none d-sm-inline-block"> Signup </span>
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/script.html
{% load static %}

<!-- MDB -->
<script type="text/javascript" src="{% static 'js/mdb.umd.min.js' %}"></script>